---

- name: Create directories
  include_tasks: create-init-directories.yaml
  when: docker_compose_services_directories_created is undefined or not docker_compose_services_directories_created

- name: Create docker networks
  include_tasks: create-docker-networks.yaml
  loop: "{{ docker_compose_networks }}"
  when: docker_network_created is undefined or not docker_network_created

- name: Create Gitlab data directory
  ansible.builtin.file:
    path: "{{ docker_compose_gitlab_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes

- name: Set gitlab docker compose file name
  set_fact:
    docker_compose_gitlab_file_name: "gitlab.yaml"

- name: Template a gitlab docker-compose file
  ansible.builtin.template:
    src: templates/docker-compose-gitlab.yaml.j2
    dest: "{{ docker_compose_services_directory }}/{{ docker_compose_gitlab_file_name }}"
  notify: Start/Restart Gitlab

- name: Flush handlers
  meta: flush_handlers
