---

- name: Start/Restart Gitlab
  ansible.builtin.command:
    cmd: "docker compose -f {{ docker_compose_gitlab_file_name }} up -d --force-recreate"
    chdir: "{{ docker_compose_services_directory }}"
  when: docker_compose_gitlab_stack_start
